### ISSUE TITLE
Arya Stark (core) face down duplicate not saving

### ISSUE THREAD

**Issue by jzimmer91** [throneteki/throneteki#2300] opened 2018-10-26 08:20 UTC
I've had this error happen twice now and I couldnt see it logged, but when a kill/discard effect has gone off and the only duplicate left on Arya is the facedown card, I am not being offered the chance to save her. 

I have the 'prompt to use dupes' setting on, so it may be something related to it not recognizing it as an option?  It only ever allows me to click on faceup copies if i have had multiple dupes on her.

**Comment by ystros** [comment] 2018-10-27 01:04
Thanks for the report! So far I haven't been able to reproduce this bug.

Out of curiosity, did you happen to run into the bug yesterday, or was it before that? There was a separate bug that didn't allow you to trigger dupes when prompted while there was a ["cannot trigger abilities" effect](https://thronesdb.com/find?q=x%3A%22cannot+trigger%22&sort=set&view=card) in play that has since been fixed.

**Comment by jzimmer91** [comment] 2018-10-29 09:28
Id had it happen twice over the course of a week, but i cant give you specific dates really :(  I don't think there was any cannot trigger effects, but if it happens to me again ill provide all the specifics

**Comment by ystros** [comment] 2018-11-23 19:18
Closing this for now, under the assumption it was one of the bugs that has since been fixed. Please re-open or open a new issue if you run into it again!

**Closed by ystros** 2018-11-23 19:18 UTC
Labels: Unable to reproduce
