### ISSUE TITLE
Ravages of War Plot

### ISSUE THREAD

**Issue by Kmshn** [throneteki/throneteki#2367] opened 2018-12-21 12:45 UTC
Hello,

Dont know if it is in progress or not but i just want let you know that at this time, this plot is not yet implemented. The "when revealed" s not working at all.

Otherwise thanks for all the work made until today !

**Comment by ystros** [comment] 2019-01-04 04:02
Thanks for the report! We're aware and hopefully it will be implemented soon. Closing this as it's a duplicate of #2307.

**Closed by ystros** 2019-01-04 04:02 UTC
Labels: duplicate
