### ISSUE TITLE
Valar Dohaeris bug

### ISSUE THREAD

**Issue by chrislimjiaan** [throneteki/throneteki#1821] opened 2018-03-14 14:50 UTC
Turn 3 plot reveal.
Opponent = Greyjoy, Greensight. Plot revealed = "Heads on Spike"
Me = Baratheon Rose. Plot revealed = "Valar Dohaeris"

Sequence:
1) Opp won initiative, choose to go first and trigger heads.
2) Once heads hit my Greathall.
3) Valar did not trigger.
4) Greensight triggered.

Video of the game: https://youtu.be/lNceoRdIN7Q, forward to 9:15 for the incident.

**Comment by DukeTax** [comment] 2018-03-14 14:53
Thanks for reporting. The video you linked is unavailable for me.

**Comment by chrislimjiaan** [comment] 2018-03-14 14:59
Had to verify YouTube. The video should be available now.

https://youtu.be/lNceoRdIN7Q?t=9m15s

**Comment by jbrz** [comment] 2018-03-16 20:09
the odd thing is that it was literally just passed over, it didn't appear as if Heads or greensight had anything to do with it.  Greensight triggered because of draw stage - its condition requires phase to be 'draw', so it's either something cascading from Heads on Spikes or dohaeris skipping itself with `proceedToNextStep()` - but you'd still expect it to print messages (Dohaeris has a ton of text that fires even when characters aren't selected).

This some spooky x-files level stuff.

**Comment by chrislimjiaan** [comment] 2018-03-17 21:48
I sense the Faceless men in action...

**Comment by ystros** [comment] 2018-03-18 07:50
This is indeed spooky. 👽

Thanks for including the video! So far I haven't been able to reproduce it. A few theories for anyone else looking into it.

* There may be some sort of obscure condition in `ForcedTriggeredAbilityWindow` that skips the remaining "When Revealed" ability after the first one is chosen. This might happen if the `meetsRequirements` method for Dohaeris went from returning true at the start of the prompt to false after Spikes was resolved. Though I don't immediately see what could cause that with Dohaeris.
* There may be a race condition in `ForcedTriggeredAbilityWindow`. e.g. if the button were double clicked. However, I think at best it would have done Spikes twice and then done Dohaeris as normal given the code (unless there's a problem like the previous bullet point).
* Some sort of crash in `AbilityResolver` could have cancelled the resolution of Dohaeris. However, it should have generated a "server error" message in chat (it didn't from the video), and sent us an error report (no matching report). So it wouldn't just silently fail.
* The use of Withering Cold before the new set of plots is somewhat suspicious since it's a game flow altering effect but I don't really see how it could cause this. The fact that characters were kneeling when Dohaeris was supposed to trigger doesn't seem to matter either.
* If Valar Dohaeris somehow saw no players players when it activated, it would complete with no messages at all. However, if the game is returning no players then a LOT of other things would be broken as well. Therefore this scenario is highly unlikely.

**Comment by ystros** [comment] 2018-06-26 06:48
Has anyone seen this happen again (or similar) in the past two months? We significantly changed how ability prompts, including plot reveals, work in #1911 and a few other updates, so it's possible whatever this was has been (accidentally) fixed since it was filed.

**Comment by zacchiro** [comment] 2018-06-26 09:50
Nope, I think it's fair at this point to close this as unreproducible. (And it can easily be reopened if it pops up again.) Thanks for noticing!

**Closed by zacchiro** 2018-06-26 09:50 UTC
Labels: Unable to reproduce
