### ISSUE TITLE
Hotho Humpback Reverse order

### ISSUE THREAD

**Issue by uBaHoB** [throneteki/throneteki#2985] opened 2020-05-16 09:33 UTC
It seems Hotho is with reverse order implemented. It should be Draw a card, Check reserve and not vise versa. 

Curently he first CHecks Reserve and than draws a card.

Cheers,
Ivan

**Comment by ystros** [comment] 2020-05-16 17:54
Thanks! This is a duplicate of #2878, so I'm going to close this.

**Closed by ystros** 2020-05-16 17:54 UTC
