### ISSUE TITLE
The Great Pyramid does not work

### ISSUE THREAD

**Issue by wilcovandijk** [throneteki/throneteki#3513] opened 2024-07-22 09:35 UTC
Every time a card is discarded while the great pyramid is on the board, a server error occurs and the cards do not appear under the great pyramid, as shown in the screenshot. 
![image](https://github.com/user-attachments/assets/bf5b4bf6-ee4f-49c9-8fa7-eaf9954c5aa9)

P.S.: Thank you guys for all your amazing work :)

**Comment by Patane97** [comment] 2024-07-22 09:43
@wilcovandijk I'll look into this one; it is 99% likely due to some changes I made to better accommodate for cards under other cards (like your agenda) outside of conclave scenarios.

Will look into this one sometime soon hopefully; thanks for reporting it!

**Comment by Patane97** [comment] 2024-08-21 08:07
@wilcovandijk I tried replicating this locally and nothing seems to be causing server errors to crash my game. Can't really fix the issue if I cannot replicate it locally. :(

Tried to replicate this with a single discard (Consuming Flames) and multi discard (incinerate):
![msedge_eHddVsuatY](https://github.com/user-attachments/assets/3e2f8e3d-1656-447e-9ae9-b7235628ace2)

I also tried to replicate what looked like your scenario in the screenshot above:
![msedge_2Wlu1VjFH8](https://github.com/user-attachments/assets/bdc1f37e-af0a-4af2-b8ea-8cf969f8aa0f)

I will try testing this on live tomorrow; for some reason I simply cannot connect to theironthrone.net right now to do so. If I cannot replicate this on live, I'll be closing the issue.

**Comment by Patane97** [comment] 2024-08-23 04:34
Closing this issue as I am also unable to replicate it on the live website with the same actions I see in your screenshot. Quite possible this was fixed by something else - not sure.

If it reoccurs, happy to reopen with more details to reproduce. :)

**Comment by ShakhaZulu** [comment] 2024-08-25 11:47
Hello all, 
Encountered the same issue but after some time. Pyramid worked fine with Meereen for 1 or 2 turns, and then it started bugging definitively. 
Please try testing it after severall turns.
Thank you all for the work you're doing.

![image](https://github.com/user-attachments/assets/ef5f09a4-6d1c-4330-a9f0-fdea4fd28d3f)
![image](https://github.com/user-attachments/assets/bce5add7-eed9-4486-9111-64a366ac5079)

**Comment by Patane97** [comment] 2024-08-25 12:06
I will need clear steps to reproduce this issue, as I have unfortunately put too much time into it already without being able to replicate - my above tests were done over two rounds, and doing the same will not produce the error.

If someone is able to get into a singleplayer match and replicate this with clear-ish steps, I will be able to find out what's actually happening to cause this bug.

Thanks :)

**Comment by ShakhaZulu** [comment] 2024-08-25 13:12
Hi Patane,
Managed to reproduce the crash in one turn in single player using City of Secrets. Please find attached screenshot. 

![image](https://github.com/user-attachments/assets/b44fac5a-8673-45e4-b79b-4611fdffe254)

**Comment by ShakhaZulu** [comment] 2024-10-06 14:38
Hello Patane !
Do you know if anything has been done as of late on that subject ? 
I have made a few games with the pyramid without encountering any problems and it has been great fun ! 
Was I just lucky or did you huys correct it without updating this thread ?

**Comment by Patane97** [comment] 2024-10-06 23:50
> Hello Patane ! Do you know if anything has been done as of late on that subject ? I have made a few games with the pyramid without encountering any problems and it has been great fun ! Was I just lucky or did you guys correct it without updating this thread ?

That's good to hear; we haven't added anything for this to fix it yet so maybe it was a recent update that indirectly fixed it.

Are you still able to replicate it using your steps above?

**Comment by Patane97** [comment] 2024-10-20 23:37
Closing as it seems pyramid is working currently; there will be future updates to this regardless so can re-check things at that point.

**Closed by Patane97** 2024-10-20 23:37 UTC
Labels: bug
