### ISSUE TITLE
Hotho Humpback

### ISSUE THREAD

**Issue by kilokai** [throneteki/throneteki#2916] opened 2020-01-23 17:09 UTC
Hotho Hump backs text is “Challenges Action: Each player draws 1 card. Each player checks reserve. (Limit once per round.)”

Reserve is being checked first then card is being drawn second and not in the order listed on the card.

**Comment by ystros** [comment] 2020-01-23 21:17
Thanks for the report! This is a duplicate of #2878. Closing.

**Closed by ystros** 2020-01-23 21:17 UTC
