### ISSUE TITLE
Wrong interaction between Morghulis and Prized keyword

### ISSUE THREAD

**Issue by LaranSoft** [throneteki/throneteki#3393] opened 2023-06-27 13:13 UTC
As pointed out by Odrl [here](https://discord.com/channels/793188949144764447/853644798706450472/1122676251589623858), there is a bug in the interaction between Morghulis and Prized keyword.

Easy way to reproduce:
Player A has a character in play with 14 power
Player B has a Prized 1 character in play (for example a >= 6 cost character with Aloof and Apart Agenda)

Player A reveals Valar Morghulis, Player B reveals any plot.

If Player A is chosen as first player, then the game proceed as expected.
Il Player B is chosen as first player though, then Player A wins the game.

This is a bug, because Player A should never win the game in this situation, regardless of the first player choice.

**Comment by LaranSoft** [comment] 2023-06-27 13:36
Investigated on this one.

The problem is caused by the characters of first player dying before the characters of second player. 

Don't know exactly the correct way to handle this (I imagine two solutions at least).

I will propose a solution that, even if not so elegant in my opinion, actually could solve the problem at hand without twisting too much the engine.

The idea is to change the method `getTotalPower` of `player.js` from

`let cardPower = card.powerOptions.contains('doesNotContribute') ? 0 : card.getPower();`

to 

`let cardPower = card.powerOptions.contains('doesNotContribute') || card.isGoingToDeadPile() ? 0 : card.getPower();`

so that cards that are `goingToDeadPile` (improvable method name :)) cannot contribute to power total.

How to check if a card `isGoingToDeadPile`? First idea was to reuse the existing flag `inDanger` but I think that a better idea is to actually create a new flag to handle this specific condition. For example:

When `promptForDeadPileOrder` method of `KillCharacters` is executed, all cards that are going to die will have this flag switched on, and after the card is actually moved to the dead pile (method `moveCardsToDeadPile` of `KillCharacters`) the flag is switched off.

Tried this solution locally and it actually works in solving the bug.
@ystros, @Patane97 let me know if this can be acceptable: eventually I will open a DPR. 

Thank you :)

**Comment by Patane97** [comment] 2023-06-28 01:17
I'm not sure I agree with the above solution, primarily as any effect which simultaneously does something (eg. Valar M simultaneously killing each character) should not be checking the "win state" (which uses `getTotalPower`) until that simultaneous effect has completed.

Without digging deeply into the code (unfortunately don't have much time to recently), I do wonder if updating Valar M to use `GameActions.simultaneously` with `GameActions.kill` on each character in play would innately resolve this, as I don't _think_ the "win state" would be checked until that simultaneous gameaction fully resolves. Realistically I would start with that adjustment (as it will need to be updated to a `GameAction` eventually anyway), and check if the "win state" is checked in-between each kill.

**Comment by LaranSoft** [comment] 2023-06-28 22:49
I confirm that Prized is configured to listen for `onCardLeftPlay`, so I think the problem is not there.

I tryed locally to change Valar Morghulis to use GameActions.simultaneously and GameAction.kill for each character in play, and it seems to fix the bug, proving that your intuition about simultaneous actions is correct :) 

There is a problem though: with the new implementation, the prompt for dead pile order is not appearing anymore.

Not sure if I'm doing something wrong here, but I think that actually there exists two ways to kill characters: 

1) `GameActions.kill` - used only by 4 cards: `LadyStoneheart`, `MagTheMighty`, `WarScorpion`, `BattleOfTheCamps`
2) `game.killCharacter`/`game.killCharacters` - used by the majority of cards (for example by `PutToTheSword`, `WildfireAssault`, `ThePaleMare`, ...)

The method 2) handles the "prompt for dead pile order" and uses the class `KillCharacters` which in turn uses a `game.raiseSimultaneousEvent` to kill each character. This method, despite the "simultaneous" word in its name, somehow checks the `postCalculation` after each single event resolution.

The method 1) seems to respect the simultaneity of actions, without checking `postCalculations` in the middle, but it handles the kill process in a different manner, with different code.

**Comment by LaranSoft** [comment] 2023-07-02 23:11
Did other investigations on this theme.

There are two distinct things to address: 
1) when multiple characters are dying simultaneously, for each of them the game engine should raise atomically three events: `onCharacterKilled`, `onCardLeftPlay` and `onCardPlaced` (this last one with location = `dead pile`), to handle correctly saves and other interrupts (as confirmed by Odrl [on Discord](https://discord.com/channels/793188949144764447/853644798706450472/1124675710196383824))
Actually none of the two existing ways to kill characters (the old `game.killCharacter`/`game.killCharacters` and the new `GameActions.kill`) handles those three events perfectly: 
a) the old way raise a `onCharacterKilled` followed by `onCardLeftPlay` and `onCardPlaced`. When I say "followed by" I mean that between those events happens a `postEventCalculations`, meaning that those events are not handled atomically.
b) the new way raise atomically `onCharacterKilled`, `onCardLeftPlay` and only if characters is really killed (not saved, not cancelled, ...) `then` the `onCardPlaced` event is raised. While this is not 100% accurate (because the Interrupt window should be the same for all three events) there is no real issue here, because no existing card interrupts a dead pile placement and likely no such a card will never exists (see previous linked Discord discussion for details)
2) After saves / interrupts, when the final set of character that are actually going to be killed has been determined, the game engine should prompt for dead pile order if two or more characters are entering the same dead pile.
In this case the old way handles correctly this situation, prompting conveniently players for dead pile order. Notice that the prompt happens in the middle of `onCharacterKilled` and `onCardLeftPlay` + `onCardPlaced` events: after all, we need to know the dead pile order _before_ starting placing cards in dead pile. This prompt is the thing that actually breaks the atomicity of events in the old way.
The new way, though, acts on single character. To kill many characters at the same time, we need to wrap `GameActions.kill` inside a `GameActions.simultaneously`, but the prompt for dead pile order is not handled at all. But there is more: even if `GameActions.kill` is refactored to handle _N_ characters instead of _1_, the crux of the issue still remains. AFAIK, insertion of a prompt in the middle of the events resolution cannot be done atomically. In other words, inserting a prompt in the `GameAction.kill` will break the atomicity of the events, nullifying the fix.

I implemented locally a different solution: a `DeadPileObserver`. Similar to `PrizedKeywordListener`, this observer is created once on game initialization and observes Dead Piles between two `postEventCalculations`. If two or more characters enters the same Dead Pile in the middle of two `postEventCalculations` - regardless of the reason - the DeadPileObserver will prompt the player to choose the order. This happens `after` cards entered dead pile.

Did some test with this solution and it seems to work. All jasmine tests are passing, with an important exception. Switching `Valar Morghulis` to use `Game Actions` instead of `handler` means that, if no characters are in play when VM is revealed, then `When Revealed` ability of VM is not registered anymore because if fails the `canResolve()` check. This is breaking the `At Prince Doran Behest` test suite. 
After another investigation on game rules (see [here](https://discord.com/channels/793188949144764447/853644798706450472/1124993422772666398)), the problem is in the `ForcedTriggeredAbilityWindow`, which inherits the method `registerAbility` from `BaseAbilityWindow`. This is wrong, because for `Forced Triggers` (which includes `When Revealed` abilities) the check `ability.canResolve(context)` should be skipped. In other words, the game should register `Forced Triggers` even if they cannot initiate, giving the FP the opportunity to be prompted for the resolution order. 
This means that `ForcedTriggeredAbilityWindow` should redefine the method `registerAbility` and skip that check. With this change, all jasmine tests are ok...

...with a final exception: `Forced Interrupt` and blank effect interaction (like `Gold Cloaks` and `Nightmares`). The check for `card.isAnyBlank()` is done in the `canResolve()` method, so if we skip that check then blanked card actions are always registered. In my opinion, the `card.isAnyBlank()` check should not be done inside of `canResolve()` method - it is not a play requirement or restriction, after all. When a card is blanked, its abilities ceases to exists temporarily, so they should stop listening for events in first place; for sure, they should not attempt at all a game registration. Instead, what is happening today is that a card ability (from a blanked card) attempts a game registration trusting on subsequent failing check `card.isAnyBlank()` made inside the `canResolve()` check.
To address this final problem, the `eventHandler` method inside the `triggeredAbility.js` class should check if `card.isAnyBlank()` and eventually `return` before calling `game.registerAbility` method.

With this final twist, all jasmine test passes and the fix seems to work properly.

Let me know if this solution can be explored, I will be happy to eventually open a DPR with this changes :)

**Comment by Patane97** [comment] 2023-07-03 00:56
@LaranSoft Forgot to respond to your first response here, so apologies if this tracks back a bunch of investigation work you've done afterwards; been super busy.

> The method 2) handles the "prompt for dead pile order" and uses the class `KillCharacters` which in turn uses a `game.raiseSimultaneousEvent` to kill each character. This method, despite the "simultaneous" word in its name, somehow checks the `postCalculation` after each single event resolution.

This is a good point in saying that there's no way for us to choose the order when `GameActions.Simultaneous(...GameAction.Kill)` is performed, so this would just be a feature gap with GameActions (as they aren't fully implemented yet, we can expect these). I would not suggest implementing new handlers or listeners here, when this could (and realistically should) be handled entirely within `GameActions` itself; primarily in regard to choosing the order of those simultaneous actions. So this would require an engine change in that regard, likely in the form of the following:

Alter `GameAction.Kill` to allow for an array of cards to be given, rather than just one. Within that gameaction it should, if more than 1 card is given, prompt the player to choose the order, **then** perform a child `onCharacterKilled` event on each of those cards in the order given. This would still ensure that any events that are tied to `onCharacterKilled` would work as intended, but should also allow for that kill-order. We already have examples similar to this in the form of `DrawCards` and `RevealCards`, as they both need some logic before actually performing those inner actions; you could use these as examples on how to achieve this. I *think* `RevealCards` also has a prompt to "ackowledge" the revealed cards, which would be similar to a prompt to choose order.

Apologies if this undermines work you've already done on this; would be happy to advise on or review a Draft PR on the above. :)

**Comment by LaranSoft** [comment] 2023-07-04 20:59
No need to apologize: all of my investigations are helping me understanding better the engine, so no work has been wasted ;)

I opened a DPR on this :) I'm expecting many rework on that, but maybe it could serve as a base.

**Closed** 2024-01-09 08:48 UTC
