### ISSUE TITLE
Mission in Essos still works even if the character was not returned to hand

### ISSUE THREAD

**Issue by arielbh** [throneteki/throneteki#3356] opened 2023-03-05 12:14 UTC
Expected: 
The character can be saved from leaving play (by a duplicate, for instance). If that happens, the post-then aspect of the effect does not resolve, so you cannot search for anything. (See [The word "Then"](https://thronesdb.com/rulesreference#The_word_Then).)

**Comment by Patane97** [comment] 2023-06-13 00:15
I've tested this on the live website, and it doesn't seem like it behaves this way; using a duplicate to save the character successfully prevents the "then" of Mission in Essos:
![image](https://github.com/throneteki/throneteki/assets/23492047/c4f63b96-4f45-43cc-8a0e-f97745a53b80)

If you are able to provide more detail in the specific scenario in which this happened, feel free to re-open or create a new issue. Will be closing this as "unable to reproduce".

**Closed by Patane97** 2023-06-13 00:15 UTC
Labels: unable to reproduce
