### ISSUE TITLE
Dorea Sand

### ISSUE THREAD

**Issue by JedatKinports** [throneteki/throneteki#2326] opened 2018-11-22 15:51 UTC
I couldn't select another character in order to return it to it's owners hand. I had one "Sand Snake" character in play meaning that I should be able to return an character with printed cost 1 or lower to it's owners hand.

![2018-11-21_20h00_22](https://user-images.githubusercontent.com/25081989/48955252-3fff0d00-ef4d-11e8-9afc-fe8d961da1f0.png)

**Comment by ystros** [comment] 2018-11-23 16:48
Thanks for the report! Offhand, I'm not able to reproduce this bug.

1. Were your prompted at all to trigger Dorea's ability?
2. Was there a valid printed cost 1 character in play to be returned (you won't be prompted if there wasn't)?
3. Did the opponent have out anything that could prevent abilities from triggering (Fortified Position blanking Dorea as soon as she enters play, King in the North preventing character abilities, etc)?

If you see this bug again, taking a screenshot right after it happens would be helpful.

**Comment by JedatKinports** [comment] 2018-11-23 17:31
I can't remember the exact scenario anymore. I should have written it down. But now looking at the screenshot, I might have forgotten to click on the card in order to trigger the ability. I'm really not sure anymore. If you can't reproduce it, then it probably works fine. This was probably a mistake on my end. :)

Next time I will provide more info.

**Comment by ystros** [comment] 2019-01-04 01:05
Closing this for now. Definitely re-open or open a new issue if you see this again!

**Closed by ystros** 2019-01-04 01:05 UTC
Labels: Unable to reproduce
