### ISSUE TITLE
Someone Always Tells vs Summer Harvest

### ISSUE THREAD

**Issue by imrahil327** [throneteki/throneteki#2020] opened 2018-06-07 18:20 UTC
In a game yesterday, I played Trade Routes vs my opponent's Summer Harvest, and was chosen as the first player.  I triggered Trade Routes first, then canceled the When Revealed of Summer Harvest with Someone Always Tells.  However, my opponent still ended up receiving gold, instead of the 0 they should have gotten.

**Comment by ystros** [comment] 2018-06-23 17:56
Thanks for the report! Unfortunately, I haven't been able to reproduce this. When I try to cancel Summer Harvest with Someone Always Tells, the player collected 0 gold as expected.

If you can remember (I realize this has been open awhile), were there any other weird circumstances? e.g. did you cycle through all plots so that the opponent had played Summer Harvest twice in a single game? Did they have out other gold modifiers such as Roseroads that would account for the gold they got?

Have you seen this behavior in games since then?

**Comment by ystros** [comment] 2019-01-04 03:50
Closing this issue since it's a bit old and we weren't able to reproduce it. If it occurs again, please re-open or open a new issue with more details!

**Closed by ystros** 2019-01-04 03:50 UTC
Labels: Unable to reproduce
