### ISSUE TITLE
Bug new Tarle/Drowned Prophet combination

### ISSUE THREAD

**Issue by Lobotom01** [throneteki/throneteki#3485] opened 2024-05-16 15:57 UTC
Hello, wanna report a possible bug

In FAQ is write i can use Drowned prophet ability twice with Tarle from last pack, but on TiT, i can put character from first interrupt into play, still can kill prophet second time, but hes not iniciate second interrupt...

In uploded sceenshot should be 2 dead characters, if i understand rules right on thronesDB 

![Bez názvu](https://github.com/throneteki/throneteki/assets/170023625/951657da-25a4-4116-8f5f-e1465c92aa97)

Thanks for response!

**Comment by Patane97** [comment] 2024-05-18 05:51
Thanks for the detailed report @Lobotom01 - really helps understand the cause behind this.

I have a sneaking suspicion that this sort of incorrect logic will be fixed once I eventually get around to addressing a more engine-level issue as part of https://github.com/throneteki/throneteki/issues/3443 (essentially by handling the triggering of simultaneous things more accurately, such as "killed", "placed in dead pile", and "leave play" all happening at the same time.

Will create a test for this to pass once the above issue is almost resolved. :)

**Comment by Patane97** [comment] 2024-05-29 07:41
@Lobotom01 I have personally tested this on the live website, and it works as intended - I have still added a test in our website regardless to make sure it _continues_ to work.

I think I might actually see your situation in the screenshot above is not actually what the FAQ describes; Drowned Prophet can only trigger if you choose for it to come back into play, not the card you placed in your dead pile.

For example, these are the steps you'd take to follow the FAQ example:
1 Kill your Drowned Prophet, and trigger it to put a card in your dead pile (do not trigger Tarle on this card being placed)
2. After the "kill" is resolved on Drowned Prophet, trigger Tarle on the Drowned Prophet to put it back into play
3. As part of Tarle's "Then" ability, choose and kill Drowned Prophet
4. Trigger Drowned Prophet again to put another character in your dead pile

I am marking this issue as closed, as it is not a bug & proven to work on TiT (with a test added anyway for safe measure).

**Closed by Patane97** 2024-05-29 07:41 UTC
Labels: bug

**Comment by Lobotom01** [comment] 2024-05-31 12:14
@Patane97 Thanks for solving :)
I dont want to argue...You saing this : I think I might actually see your situation in the screenshot above is not actually what the FAQ describes; Drowned Prophet can only trigger if you choose for it to come back into play, not the card you placed in your dead pile......
But i think, that FAQ saing somethink different - If you use [Drowned Prophet](https://thronesdb.com/card/12013) to place a Drowned God character in your dead pile, then use **_Tarle to put that character into play, this will all happen before Drowned Prophet actually leaves play. That means you can then **kill Drowned Prophet again** in the post-then part of the effect, and trigger it **again**_** to put another character in your dead pile.

The exaple you wrote, i agree with it, if i target Drowned Prophet on Tarles reaction...but FAQ saying, that you targeting character from prophet reaction, not prophet self...and then that char coming into play, im killing Prophet again and FAQ saing i can trigger his reaction one more
I can explain it on testing game if You want, or we can comunicate via discord
