### ISSUE TITLE
Rickon cancell

### ISSUE THREAD

**Issue by Laplante1** [throneteki/throneteki#2291] opened 2018-10-20 18:56 UTC
Rickon's ability allows you to cancel any effect (including your own) with the word "search" currently you can cancel only opponent's ability.

**Comment by ystros** [comment] 2018-10-20 19:19
Thanks! This is an exact duplicate of issue #2141. 

It might be helpful if you add a comment on that issue describing your reasoning for wanting to cancel your own searches. I suspect it's just to get the extra sacrifice trigger off Rickon, but any additional info on your reason could be helpful on how to prioritize us changing the current behavior.

**Closed by ystros** 2018-10-20 19:19 UTC

**Comment by zacchiro** [comment] 2018-10-20 19:34
@ystros: I've just done so in that issue, as I agree times have changed, and this is now particularly useful with Qohor + sacrifice shenanigans.
