### ISSUE TITLE
Improvement: In Decks section select multiple + Delete option and retain detail view on the right

### ISSUE THREAD

**Issue by chris-torruella** [throneteki/throneteki#3518] opened 2024-07-23 10:50 UTC
To help deck management:
1. Possibility to select multiple decks and bundle delete
2. Retain the deck detail view on the right regardless of scroll
<img width="1728" alt="Screenshot 2024-07-23 at 20 50 33" src="https://github.com/user-attachments/assets/87318950-c17c-41cb-a01c-00bb08cbbdf4">

**Comment by Patane97** [comment] 2024-10-20 23:32
This has been implemented on the development version of the site, except deck details are only viewed when you open the deck editor (by design).

Marking this as closed, as it's fixed in an upcoming release.

**Closed by Patane97** 2024-10-20 23:32 UTC
Labels: enhancement
