### ISSUE TITLE
Faceless Men No Attachments keyword

### ISSUE THREAD

**Issue by colonialbob** [throneteki/throneteki#1663] opened 2017-12-30 22:37 UTC
My opponent played Traitor to the Crown (a condition) on my Faceless Men, and then I copied his City Watch. My Faceless Men should have gained "No Attachments except Weapon", but the Traitor did not fall off.

**Comment by DukeTax** [comment] 2017-12-30 23:38
Thanks for reporting. :) He gained the keyword, but the issue here is attachments not continuously checking parent restrictions once attached. Duplicate of #1319.

**Comment by ystros** [comment] 2017-12-31 02:43
Actually, it appears to be both. "No Attachments" isn't coded like other keywords (it isn't returned in `getPrintedKeywords`, it's stored in `allowedAttachmentTrait` on the card), so unless I'm missing something the Faceless Men's ability doesn't currently copy it properly. Even if it did, as stated above gaining keywords doesn't currently re-check attachment validity, so it still wouldn't have kicked the attachment off.

This is also a problem with Patchface + Ser Dontos (Patchface gains keywords, so should gain "No attachments except Weapon" from Ser Dontos).

Thus, re-opening the issue.

**Closed** 2018-06-08 08:54 UTC
