### ISSUE TITLE
Ability targets that need to be limited to the play area

### ISSUE THREAD

**Issue by sirajch** [throneteki/throneteki#2159] opened 2018-08-17 16:03 UTC
Hi, i don't know if this is reported or not, i dont see it in actual issues, so...

For example Jonas Slynt: https://thronesdb.com/card/11006
Explanation of sacrifice: https://thronesdb.com/rulesreference#Sacrifice

TheIronThrone allows player to pick a card from discard pile / hand etc. But according to rules reference: "must choose a card in play that he or she controls" etc.

**Comment by luky92** [comment] 2018-08-17 16:10
It's a common issue on thronetheteki for a card to have the ability to choose illegal targets eg growing strong can choose from discarded or dead cards

**Comment by DukeTax** [comment] 2018-08-18 14:49
True, there's probably a whole bunch of cards which don't limit their ability target to the play area, which is made more noticeable ever since targettable piles open up. If you know any more of these please mention them here. Thanks for reporting.

[ ] Janos Slynt (NW)
[ ] Growing Strong

**Comment by sirajch** [comment] 2018-08-20 05:12
Drowned God Fanatic

**Comment by DukeTax** [comment] 2018-08-20 20:11
Hmm, you must mean the prompt to choose a character to kill as a cost, but I can't reproduce that. Can you elaborate?

**Comment by sirajch** [comment] 2018-08-21 04:40
I think his action allows to choose characters on hand, but not sure right now.

Action: Kill a character to put Drowned God Fanatic into play from your dead pile. (Max once per round.)

**Comment by sirajch** [comment] 2018-08-21 04:42
I will focus on this on my next game and I will respond again.

**Comment by mplain** [comment] 2018-10-19 06:33
Janos Slynt still allows sacrificing chars from the dead pile.

**Comment by zacchiro** [comment] 2018-10-19 07:32
I noticed this bug report only after reacting to @mplain bug report about Janos on discord. But here we go:

- Janos Slynt #2286 
- Growing Strong #2287 

I suggest we close this catch-all bug report and use per-card bug reports instead, as they make easier to track progress.

**Comment by ystros** [comment] 2019-01-04 04:09
As mentioned above, let's file any further illegal-target bugs separately. Closing this issue.

**Closed by ystros** 2019-01-04 04:09 UTC
