### ISSUE TITLE
core randyll tarly + dragonglass dagger doesn´t work

### ISSUE THREAD

**Issue by EvadLhorg** [throneteki/throneteki#3247] opened 2022-04-23 13:45 UTC
our all time favourite bug is back again: randyll tarly + sworn to the watch + dragonglass dagger => can´t trigger his reaction when he is declared as an attacker/defender

**Comment by Patane97** [comment] 2022-09-08 04:48
Duplicate of #3191. Closing this one.

**Closed by Patane97** 2022-09-08 04:48 UTC
Labels: bug
