### ISSUE TITLE
No prompt to use Priviledged Position in marshalling

### ISSUE THREAD

**Issue by sergselin** [throneteki/throneteki#2616] opened 2019-06-14 09:05 UTC
Hello, I sometimes do not get a prompt to use Priviledged Position in the marshalling phase.

Example below.

![Снимок](https://user-images.githubusercontent.com/39171688/59497660-8d68aa80-8e9c-11e9-9e9c-8a342e184134.PNG)

**Comment by Odrl7** [comment] 2019-06-14 15:15
Yes, this happens when you have lost a power challenge in the previous challenges phase. You are not prompted to use Privileged Position again until you get to the next challenges phase.

It's sometimes problematic with cards like Meereen, for example, because you can't really undo them once they are triggered.

**Comment by sergselin** [comment] 2019-06-14 18:54
> Yes, this happens when you have lost a power challenge in the previous challenges phase. You are not prompted to use Privileged Position again until you get to the next challenges phase.
> 
> It's sometimes problematic with cards like Meereen, for example, because you can't really undo them once they are triggered.

So will this be fixed or stay as a known bug?

**Comment by ystros** [comment] 2019-06-16 00:07
Thanks for the report! And thanks to @Odrl7 for helping narrow down what the problem is (challenges from the previous round counting toward the current one). I've been able to reproduce it.

Please keep in mind that The Iron Throne is something a couple people work on in their free time, outside their full-time jobs and normal lives. Such bugs are prioritized by how severe they are, how difficult they are to fix, what someone feels like working on at any given time, and must often be put aside in order to get new packs out in a timely fashion.

I think this particular bug won't be difficult to fix, and will likely be bundled with similar bugs I've seen around "challenges in a round" restrictions that have been reported. But I can make no guarantees about when it will be fixed.

Thank you for your patience.

**Comment by sergselin** [comment] 2019-06-18 20:29
@ystros totally understand it, we appreciate your work!

**Closed** 2019-06-19 16:14 UTC
Labels: bug
