### ISSUE TITLE
Mallister and Renown

### ISSUE THREAD

**Issue by mwaschak** [throneteki/throneteki#3437] opened 2023-10-19 19:22 UTC
Hello,

    I believe Mallister should be getting renown when he is defending. This does not seem to be working.

    Thanks!

**Comment by Patane97** [comment] 2024-08-21 07:07
Checked the code for both Ser Denys Mallister & Ser Jason Mallister (just to make sure), and they should be working as intended. I'd like to see this reproduced with an example if possible - in the meantime though I will be closing this issue. :)

**Closed by Patane97** 2024-08-21 07:07 UTC
