### ISSUE TITLE
Septa Lemore and Aegon Targaryen (TSC) wrong interaction

### ISSUE THREAD

**Issue by LaranSoft** [throneteki/throneteki#3420] opened 2023-09-01 07:44 UTC
If Septa Lemore and Aegon Targaryen (TSC) are killed simultaneously, TiT should prompt for Septa Lemore Interrupt.

**Comment by Patane97** [comment] 2023-09-21 00:33
I have a suspicion that this is more of an issue with Valar, or other "simultaneous kill" effects, rather than Septa Lemore. She seems to be coded correctly, however if someone Valar's & Septa Lemore is atomically killed _after_ Aegon, she will not be able to interrupt to return him.

I will close this issue, as it is technically a duplicate of #3393

**Closed by Patane97** 2023-09-21 00:33 UTC
Labels: duplicate
