### ISSUE TITLE
Archmaester Marwyn doesn't work outside of Conclave

### ISSUE THREAD

**Issue by ChannelDelibird** [throneteki/throneteki#3039] opened 2020-08-16 14:29 UTC
Look, I know. I _know_. But I did try it, and I'd like to try it again. Was using Banner of the Watch, should that matter, and when I triggered his reaction, the chat log told me it had done it, but there were no cards under my agenda.

**Comment by EvadLhorg** [comment] 2020-08-17 15:34
Duplicate of #2942

**Comment by EvadLhorg** [comment] 2020-08-17 15:35
Thanks for the report and bringing this up again!

**Comment by Patane97** [comment] 2024-07-03 02:54
Added/resolved in #3502

**Closed by Patane97** 2024-07-03 02:54 UTC
