### ISSUE TITLE
Core Sansa and Core Stannis

### ISSUE THREAD

**Issue by SteliosCh21** [throneteki/throneteki#2387] opened 2019-01-09 21:23 UTC
Opponent had core Stannis and during the standing phase, when I chose core Sansa to be one of my two characters, she didn't gain power for the faction card. She hadn't used this ability previously during that round.
![thumbnail_20190109_215924](https://user-images.githubusercontent.com/46503013/50929126-223a2880-1465-11e9-93e5-653219a5fa6e.jpg)

**Comment by ystros** [comment] 2019-01-10 04:01
Thanks for the report, and especially for adding a screen! However, I haven't been able to reproduce this. When standing Core Sansa while Core Stannis was out (either by choosing to stand her if there were 3 or more knelt characters, or auto-standing her if there were 2 or less knelt characters), I was prompted to trigger her ability:
![screen shot 2019-01-09 at 7 56 37 pm](https://user-images.githubusercontent.com/145077/50945249-bcd83e80-1448-11e9-8567-3bbb8c38103b.png)

Was there any lag while you were playing? The only thing I can think of is when you chose the characters to stand, the 'Done' button was clicked twice, skipping over the 'Any reactions?' prompt.

**Comment by ystros** [comment] 2019-03-02 18:21
Closing this issue since we weren't able to reproduce it. Please re-open if you encounter it again!

**Closed by ystros** 2019-03-02 18:21 UTC
Labels: Unable to reproduce
